##############################################################################
# GitHub Actions Workflow to test building MeshPolygonization with GCC
#
# Copyright (C) 2022 Liangliang Nan <liangliang.nan@gmail.com>
#
# Licensed under GNU LGPL.3, see LICENCE file
##############################################################################
name: test-build-gcc

on: [push, pull_request]

jobs:
  build:
    name: Build with ${{ matrix.compiler }}
    strategy:
      fail-fast: false
      matrix:
        compiler:
          - name: g++-7
            version: 7
          - name: g++-8
            version: 8
          - name: g++-9
            version: 9
          - name: g++-10
            version: 10
          - name: g++-11
            version: 11

    runs-on: ubuntu-20.04

    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential cmake \
            libglu1-mesa-dev freeglut3-dev mesa-common-dev \
            libxrandr-dev libxinerama-dev libxcursor-dev libxi-dev

      - name: Install GCC version ${{ matrix.compiler.name }}
        run: |
          sudo apt-get install -y gcc-${{ matrix.compiler.version }} g++-${{ matrix.compiler.version }}
          sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-${{ matrix.compiler.version }} 100
          g++ --version

      - name: Configure and build with CMake
        run: |
          mkdir -p build && cd build
          cmake -DCMAKE_CXX_COMPILER=$(which g++) -DCMAKE_BUILD_TYPE=Release ..
          make
